apiVersion: v1
kind: ConfigMap
metadata:
  name: genai-app-config
  namespace: genai-app
data:
  APP_ENV: "production"
  LOG_LEVEL: "INFO"
  AllowedHosts: "*"
  # Add other non-sensitive configuration here
