apiVersion: v1
kind: Service
metadata:
  name: genai-app
  namespace: genai-app
spec:
  selector:
    app: genai-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
