apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: genai-app-ingress
  namespace: genai-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: genai-app.dev.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: genai-app
                port:
                  number: 80
